httpaddress: :8080
timezone: Asia/Jakarta
signaturekey: jwttoken
debug: true

dbconfig:
  host: localhost
  port: 5432
  name: db_schedule_app
  user: postgres
  password: 123456
  applicationname: latihan
  logging: true
