httpaddress: :8080
timezone: Asia/Jakarta
signaturekey: lumoshive
debug: true

dbconfig:
  host: localhost
  port: 5432
  name: db_schedule_app
  user: postgres
  password: 123456
  applicationname: schedule_app
  logging: true
  maxopenconn: 50
  maxidleconn: 10
